<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'KeyValueStorage\Module'                 => __DIR__ . '/Module.php',
  'KeyValueStorage\Adapter\StorageAdapter' => __DIR__ . '/src/KeyValueStorage/Adapter/StorageAdapter.php',
  'KeyValueStorage\Factory\AdapterFactory' => __DIR__ . '/src/KeyValueStorage/Factory/AdapterFactory.php',
  'KeyValueStorage\Options\AdapterOptions' => __DIR__ . '/src/KeyValueStorage/Options/AdapterOptions.php',
);
